#  NodeJS build with cypress
# Test only of code. No actual deployment

image: cypress/base:12

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - node
          - cypress
        script:
          - npm install -g npm@latest
          - npm --version
          - npm install
          - npx cypress install
          - npm run lint
          - npm run dev &
          - npm run e2e:record -- --ci-build-id $BITBUCKET_BUILD_NUMBER --key $CYPRESS_REPORT_ID
        artifacts:
          # store any generates images and videos as artifacts
          - cypress/screenshots/**
          - cypress/videos/**
definitions:
  caches:
    cypress: $HOME/.cache/Cypress
