const availableMethods = {
  action_dispatch: true,
  data_deleteDataValue: true,
  action_ifElse: true,
  action_getActionValue: true,
  action_getBlockValue: true,
  data_getDataValue: true,
  action_getContextValue: true,
  action_getPayloadValue: true,
  action_getSequenceValue: true,
  action_setActionValue: true,
  data_setDataValue: true,
  data_generateId: true,
  data_find: true,
  component_remove: true,
  component_renderChildren: true,
  fetch_getAll: true,
  fetch_getById: true,
  list_filter: true,
  list_forEach: true,
  list_push: true,
  list_indexOf: true,
  list_sort: true,
  list_splice: true,
  operator_compare: true,
  operator_eval: true,
  query_filter: true,
  query_fetch: true,
  route_currentId: true,
  route_currentPath: true,
  route_navigate: true,
  token_textContent: true,
  bootstrapModal_create: true,
  bootstrapModal_show: true,
  bootstrapCollapse_create: true,
  bootstrapCollapse_show: true,
  bootstrapCollapse_hide: true,
  bootstrapCollapse_toggle: true
}

export default availableMethods
