const availableMethods = {
  action_dispatch: true,
  delete_dataValue: true,
  eval_condition: true,
  get_actionValue: true,
  get_blockValue: true,
  get_dataValue: true,
  get_contextValue: true,
  get_payloadValue: true,
  get_sequenceValue: true,
  set_actionValue: true,
  set_dataValue: true,
  data_generateId: true,
  data_find: true,
  component_append: true,
  component_render: true,
  fetch_getAll: true,
  fetch_getById: true,
  list_filter: true,
  list_forEach: true,
  list_push: true,
  list_sort: true,
  list_splice: true,
  operator_compare: true,
  operator_eval: true,
  query_filter: true,
  query_fetch: true,
  route_currentId: true,
  route_currentPath: true,
  route_navigate: true,
  token_textContent: true,
  bootstrapModal_create: true,
  bootstrapModal_show: true
}

export default availableMethods
